/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_team1538_lib_CowAlphaNum */

#ifndef _Included_com_team1538_lib_CowAlphaNum
#define _Included_com_team1538_lib_CowAlphaNum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_team1538_lib_CowAlphaNum
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_team1538_lib_CowAlphaNum_init
  (JNIEnv *, jclass);

/*
 * Class:     com_team1538_lib_CowAlphaNum
 * Method:    SetBanner
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_team1538_lib_CowAlphaNum_SetBanner
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_team1538_lib_CowAlphaNum
 * Method:    SetBannerPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_team1538_lib_CowAlphaNum_SetBannerPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_team1538_lib_CowAlphaNum
 * Method:    DisplayBanner
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_team1538_lib_CowAlphaNum_DisplayBanner
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
